repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
